# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default='foo', max_length=200),
            preserve_default=False,
        ),
    ]
